### ISSUE TITLE
Compile Score window crashes MSVC

### ISSUE THREAD

**Issue by b-winkler** [Viladoman/CompileScore#12]
MSVC crashes when I
- drag the Compile Score window to a docking space
- right-click a column header in the Compile Score window

Installed version is 1.5.6.

Kind regards, Benni

**Comment by Viladoman** [comment]
Good catch! 

It was an easy fix. Fix submitted in [version 1.5.6.1](https://github.com/Viladoman/CompileScore/actions/runs/552974447). I will bundle this with more future changes before submitting a new release to the marketplace.  

Thanks for reporting!

**Comment by Viladoman** [comment]
This should be fixed in 1.5.7.

Thanks for catching this!
