### ISSUE TITLE
All marker definitions have the same name

### ISSUE THREAD

**Issue by b-winkler** [Viladoman/CompileScore#15]
Hi Ramon,
all 5 highlighting definitions have the same name, which makes it quite hard to assign new colors :-)
![image](https://user-images.githubusercontent.com/53170541/109786552-8dc74d00-7c0d-11eb-9d63-139769442540.png)
Cheers, Benni

**Comment by Viladoman** [comment]
Sorry for the late reply. I finally got some time to pour into CompileScore again. 

Version 1.5.7 should have the tags updated: 
![image](https://user-images.githubusercontent.com/8118743/116839191-50485700-ab9f-11eb-9c1f-3cfc6ea036ce.png)

Now it should be easy to recolor the text highlights.
