### ISSUE TITLE
Right clicking a project and choosing "Build and Profile" fails for our projects

### ISSUE THREAD

**Issue by gpakosz** [Viladoman/CompileScore#21]
Hello,

Right clicking a project and choosing "Build and Profile fails".
<img width="352" alt="image" src="https://user-images.githubusercontent.com/553208/173203552-57f7c40a-38fb-4aea-82ff-b0c1a4293284.png">

This is likely because our `.vcxproj` files are modified to import our own `.targets` XML files in a bigger scheme that allows us to factor out build settings for the `~100` projects in our `.sln`.

Will try to come up with a repro.

**Comment by Viladoman** [comment]
Interesting. Strange that the Build and Profile is not behaving the same way as Build Project. 
If you could provide me with a simple failing test project I would really appreciate it.

**Comment by Viladoman** [comment]
I think the mentioned PR might have fixed this issue. In case it did not, there is also the option to manually trigger a 'Start Trace' and 'Stop Trace' in the extension menus ( mappable to key bindings or custom toolbar buttons )
