### ISSUE TITLE
No results when profiling a build using the MSVC 2015 toolchain

### ISSUE THREAD

**Issue by missmah** [Viladoman/CompileScore#22]
What's the minimum MSVC toolchain this works with? I started data collection, ran a build which uses the compiler and linker from MSVC 2015, stopped data collection, and ended up with a 1K .scor file which when loaded seems to contain no data.

Does this have a minimum compiler version e.g. 2019 toolchains?

**Comment by missmah** [comment]
I just tested with the vs2019 toolchain in our build and it did generate data, so this seems to be confirmed on my end as likely.

**Comment by Viladoman** [comment]
That's right. The MSVC recorder is using the [Microsoft C++ Build Insights SDK](https://docs.microsoft.com/en-us/cpp/build-insights/get-started-with-cpp-build-insights?view=msvc-170). As far I know this got introduced on MSVC version 16.1. Then on version 16.4 they added Template instancing data. I might be slightly wrong with the exact versions, but at least you can have a rough estimate.

**Comment by missmah** [comment]
My minor suggestion would be to put this in a minimum requirements section or notes section in the project readme. It's not a surprising thing in the end, but knowing it up-front would be nice :)
