### ISSUE TITLE
Feature Request: Support Zooming in/out of the timeline view with the mouse-wheel

### ISSUE THREAD

**Issue by missmah** [Viladoman/CompileScore#27]
This would make working in the timeline view visualization much more efficient/user-friendly compared to having to manually click on the zoom control and up/down/left/right arrows.

**Comment by Viladoman** [comment]
There should be timeline zoom control with the mouse wheel. Unless I broke something :D

Try **Ctrl + Mouse Wheel** while hovering the timeline. 

![Timeline image](https://github.com/Viladoman/CompileScore/wiki/data/CompileScoreTimeline.gif?raw=true)
