### ISSUE TITLE
Clash of colour highlighting with git diffs

### ISSUE THREAD

**Issue by kamrann** [Viladoman/CompileScore#34]
It's a minor issue, but the colouring of `#include`s leads to confusion when using Visual Studio's built-in `git diff` features. At a glance, it looks like all includes are source code changes.

I wonder if the context (diff vs regular view) is exposed by VS so that the extension can optionally disable the annotations? Failing that, just a simpler way to toggle the annotation functionality (a toolbar button or keyboard shortcut) would be useful.

**Comment by Viladoman** [comment]
Good point! 
I don't use the VS built-in git diff, but I will have a look and see how bad it is. Meanwhile there are some ways exposed to change the colors or disable the highlights through the Visual Studio options. [Text Highlight wiki](https://github.com/Viladoman/CompileScore/wiki/Text-Highlight-Customization)

I agree that if it can conflict with other tools having a shortcut/button can be really useful.

I am not sure when I will have time to look into this thou. I you feel like playing around the [Glyph Tagger](https://github.com/Viladoman/CompileScore/blob/master/CompileScore/Shared/Glyph/ScoreGlyphTagger.cs), is where the simple regex markup happnes. There is already a toggle from the settings, we just need to hook that up to action too,

**Comment by Viladoman** [comment]
There is a direct action to toggle text highlight visibility now: Compile Score / View / Toggle Text Highlight
This can be mapped to a key combo or toolbar icon if wanted.
