### ISSUE TITLE
release packaging

### ISSUE THREAD

**Issue by Trass3r** [Viladoman/CompileScore#53]
https://github.com/Viladoman/CompileScore/releases/tag/v1.9.1
Looks like CompileScoreApp.zip is missing CompileScore.dll and CompileScore.runtimeconfig.json.
Took it from https://github.com/Viladoman/CompileScore/actions/runs/7615943981 and it works.

**Comment by Viladoman** [comment]
Oh no! It looks like I made a mistake when writing the Release github action.
Thanks for letting me know.

**Comment by Viladoman** [comment]
Just submitted and updated Release.yml to zip the needed files. 
Thanks for reporting this!
